In [ ]:
import pandas as pd
import numpy as np

In [ ]:
X = pd.read_csv(X_Final.csv)
Y = pd.read_csv(Y_Final.csv)

**Grouping on ISG - X**

In [ ]:
X_3d = X.copy()

In [ ]:
X_3d = X_3d.drop(columns = 'Unnamed: 0')

In [ ]:
X_3d = X_3d.set_index(['CCM_TEC/ISG', 'SLAB_ID', 'ZOB_ID' ])

In [ ]:
X_3d

**Grouping on ISG - Y**

In [ ]:
Y_3d = Y.copy()

In [ ]:
Y_3d = Y_3d.drop(columns = 'Unnamed: 0')

In [ ]:
Y_3d = Y_3d.set_index(['CCM_TEC/ISG', 'SLAB_ID'])

In [ ]:
Y_3d

**Creating 3d_Array**

In [ ]:
X_3d_arr = np.array(list(X_3d.groupby('CCM_TEC/ISG').apply(pd.DataFrame.to_numpy)))
X_3d_arr.shape

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.

(54,)

In [ ]:
Y_3d_arr = np.array(list(Y_3d.groupby('CCM_TEC/ISG').apply(pd.DataFrame.to_numpy)))
Y_3d_arr.shape

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.

(54,)